### ISSUE TITLE
Expand hitbox of 5 minute increment numbers

### ISSUE THREAD

**Issue by jfkw** [catc/react-timekeeper#1]
This looks great. One difference from Android time input that was immediately noticeable was the high precision selection of minutes. With the mouse, I almost always get the exact nearest minute. With the native Android control, most taps select on a 5 minute increment, but individual minutes are selectable if you point carefully or drag.

react-timekeeper's control would feel a little more like that if the hitbox of 5 minute increments was somewhat larger that currently.

**Comment by catc** [comment]
Added in https://github.com/catc/react-timekeeper/pull/19
