### ISSUE TITLE
NPM package contains original files next to the transpiled ones

### ISSUE THREAD

**Issue by pokonski** [catc/react-timekeeper#10]
Hey @catc 

I encountered a bug where doing `import TimeKeeper from 'react-timekeeper';`

results in an error:

![image](https://user-images.githubusercontent.com/135402/33807245-dd1e4fa6-ddd3-11e7-907e-b6397418fd46.png)

Because the NPM package contains both the .jsx and compiled .js file. That in turn confuses webpack into loading the original, instead of compiled.

Can this be fixed?

**Comment by pokonski** [comment]
A bypass for this would be to force babel-loader to trans-pile just `react-timekeeper` package, but it's an ugly exception to make.

**Comment by catc** [comment]
If you're using babel-loader, have you tried adding [transform-object-rest-spread](https://babeljs.io/docs/plugins/transform-object-rest-spread/)? Lemme know if that fixes it.
