### ISSUE TITLE
12:xx AM times are being returned as 24:xx in 24 hour format

### ISSUE THREAD

**Issue by snazzypants** [catc/react-timekeeper#13]
12:xx AM times are being returned as 24:xx in 24 hour format, when it should be 00:xx

**Comment by catc** [comment]
Should be fixed by https://github.com/catc/react-timekeeper/commit/17c8a555fdc92b1d0543893a5667012695b4572c

**Comment by snazzypants** [comment]
Thanks for the quick reply. I've updated to the latest version, and the 12:xx AM are reporting correctly.  

However, it seems that the 12:xx PM times are now reporting as 24:xx in 24 hour format (when it should be 12:xx)

**Comment by catc** [comment]
Ha, good catch. I'll write more tests to account for it.
