### ISSUE TITLE
Get time on onDoneClick

### ISSUE THREAD

**Issue by tagyoureit** [catc/react-timekeeper#16]
Hi,
I'd like to use this component in my app.  What I want to do is make a single external API call after the done button is clicked.  

Currently, I only see that the time is returned via the onChange event and that it returns after both the hours and minutes are selected.

What is the best way to return time after the minutes are selected?  (eg with onDoneClick or only when minutes are selected or have a function I can call to retrieve the time)

thanks,
tag

**Comment by catc** [comment]
Added in https://github.com/catc/react-timekeeper/pull/19
