### ISSUE TITLE
Make `coarseMultiplier` configurable

### ISSUE THREAD

**Issue by pierrecholhot** [catc/react-timekeeper#22]
I am trying to set minutes to span to `15` minutes intervals instead of `5`.

Is it possible to add `coarseMultiplier` in the `config` ? Or maybe the entire `CLOCK_DATA` object ?

https://github.com/catc/react-timekeeper/blob/master/src/helpers/data.js#L15

**Comment by catc** [comment]
Thanks for the suggestion. I'll try to add the option in the next update.

**Comment by catc** [comment]
Added in #25
