### ISSUE TITLE
Demo page showing 60 minutes on Android devices

### ISSUE THREAD

**Issue by wggley** [catc/react-timekeeper#26]
When testing demo pages I can put minutes dial to 60 minutes.

See attached image
![Screenshot_20190924-103158_Chrome](https://user-images.githubusercontent.com/13734836/65516190-efcb4100-deb6-11e9-8270-917ebedb3bf6.jpg)

**Comment by catc** [comment]
Should be an easy fix - I'll have something out tonight. Let me know if you find any other bugs.
