### ISSUE TITLE
Found Incompatible Node

### ISSUE THREAD

**Issue by mvofreire** [catc/react-timekeeper#27]
I received this error when i try install

```js
error react-timekeeper@2.0.3: The engine "node" is incompatible with this module. Expected version "10.16.0". Got "10.16.3"
error Found incompatible module.
```

My config
node:10.16.3
yarn:1.17.3

![image](https://user-images.githubusercontent.com/4127341/65988279-e5ccb380-e45d-11e9-97f0-500fcdc346bd.png)

**Comment by catc** [comment]
Seems to be complaining about the nod engine prop in the package.json. I'll remove it tonight - can try https://github.com/gilbarbara/react-joyride/issues/131 in the meantime?

**Comment by catc** [comment]
Should be fixed by https://github.com/catc/react-timekeeper/commit/6ec4692ffcb15259555758173d8b4d9938703995#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R78
