### ISSUE TITLE
TimePicker, disable range of time

### ISSUE THREAD

**Issue by DibakarHalder** [catc/react-timekeeper#29]
Hi,

in TimePicker is it possible to disable hours and minutes? like in DatePicker with "minDate" and "maxDate" parameters, it would be useful to set the available time range,

for example TimePicker from={'9:00am'} to={'6:00pm'}

**Comment by catc** [comment]
There isn't at the moment. I'll add to list of possible future features.

**Comment by erickgtzh** [comment]
> Hi,
> 
> in TimePicker is it possible to disable hours and minutes? like in DatePicker with "minDate" and "maxDate" parameters, it would be useful to set the available time range,
> 
> for example TimePicker from={'9:00am'} to={'6:00pm'}

Is there an update about it?
Big thanks in advance!!

**Comment by HalaZbib22** [comment]
Hello, the timepicker still has no prop that allows us to disable a time range. Any update ?
