### ISSUE TITLE
Change the clock radius

### ISSUE THREAD

**Issue by gzaban** [catc/react-timekeeper#35]
First of all, thank you for your wonderful work. If there is a way that I can change from outside the clock size.

Is there a future plan to allow the change of parameters from outside?

like the CLOCK_RADIUS var

**Comment by catc** [comment]
Hey, sorry for the late reply but currently there isn't a plan to make clock radius an option. The way the library is written makes it hard to expose the clock radius while also ensuring that functionality + styles don't break.

Maybe in the future if there's enough demand I'll refactor it, but for the time being I'd suggest just forking it and experimenting with the values yourself.

**Comment by sivadinesh1** [comment]
> Hey, sorry for the late reply but currently there isn't a plan to make clock radius an option. The way the library is written makes it hard to expose the clock radius while also ensuring that functionality + styles don't break.
> 
> Maybe in the future if there's enough demand I'll refactor it, but for the time being I'd suggest just forking it and experimenting with the values yourself.

except for the radius, i am very happy with this component, a dense version will be great
