### ISSUE TITLE
switchToMinuteOnHourSelect does not work for the HOUR combobox when a selection is made

### ISSUE THREAD

**Issue by keevan** [catc/react-timekeeper#38]
This means the user needs to click on the minute _twice_ to get the combobox options to display

Expected behaviour for the options enabled
**switchToMinuteOnHourSelect={true}**

- Click twice on the hour to show the (list of) options for **hour** selection
- Upon selection change, the focus should move to the minutes, such that clicking on the minutes once should show the (list of) options for changing the **minutes**

Current behaviour:
- Click twice on the hour to show the (list of) options for **hour** selection
- Click on the minutes to change it to the "minutes" display
- Click again on the minutes to show the (list of) minute options

![2020-01-31_22-30-12](https://user-images.githubusercontent.com/9924643/73536091-4b1aca80-4479-11ea-86ec-70c2ec74d083.gif)

**Comment by catc** [comment]
Didn't know how to feel about the component auto switching to minutes so I added the `switchToMinuteOnHourDropdownSelect` to allow for this.
