### ISSUE TITLE
Feature request - Context menu click / right click to go back to the hour selection if currently in minutes

### ISSUE THREAD

**Issue by keevan** [catc/react-timekeeper#41]
If you are modifying a time, a user might want to quickly switch back to hours and update it (e.g. if they misclicked initially). They currently have to move the cursor to the hour display, and then back down to choose the hour. 

Having another option to quickly go back to the hour selector would be a great feature.

If reasonable, it might be good to have this as an option (prop) as well, and allow the user to toggle between the modes (hour + minutes) by right clicking without making a selection anyways.

**Comment by catc** [comment]
I think the effort outweighs the gain - clicking the hour is fine imo. Closing this for now.
