### ISSUE TITLE
Midnight time 24 hour mode strange behavior

### ISSUE THREAD

**Issue by ssukienn** [catc/react-timekeeper#46]
Hi, seen similar issue in closed ones but I think this one is different.

Was seeing it in most recent version of Chrome/Firefox

**Current behavior:**
- Sometimes choosing 00 hour in 24h mode is setting display to 24:xx or 0:xx (specifically when you drag pointer (without releasing) from the right side of 00 clock hour it will be 0:xx, from left side : 24:xx)
- `fomatted24` property from onChange callback is returned as `0:00`

**Expected behavior:**
- display hour is 00:xx always
-  `fomatted24` property is returned as `00:00`

![image](https://user-images.githubusercontent.com/16635781/78998477-01212580-7b49-11ea-8d1c-caef136afbe3.png)
![image](https://user-images.githubusercontent.com/16635781/78998499-1007d800-7b49-11ea-85c2-13083b0b42f0.png)

#EDIT:
Ok, I see that number in hours without leading zero for lower than 10 is by choice here. It would be perfect if you could modify the format displayed there. Personally I find hour `09:15` looking better in case of display in top bar

**Comment by catc** [comment]
Should be fixed - as for the custom format for time display, maybe i'll add it as a feature in the future.
