### ISSUE TITLE
iOS events captured twice

### ISSUE THREAD

**Issue by erpheus** [catc/react-timekeeper#47]
If using an iOS device (tested on safari iOS 13 on iPhone and iPad) a simple tap to choose an hour will also select the minute with the closest placement.

This behavior is not so bad if the picker does not close itself, but I built one with the option `closeOnMinuteSelect` enabled and what happens is that with one tap both get selected and the picker closes. Thus the only choosable times are 12:00, 1:05, 6:30, etc...

This does not happen if instead of tapping the finger is held, dragged around and released.

I inspected the events firing in mobile safari and it seems like there are both touch and click events going on. My guess is that there is a `preventdefault` call missing in the touchstart or touchdown events, that would tell iOS not to generate a click one as well, but I'm not sure. I haven't tested it deeply.

Here is a screencast showing the problem. I'm only clicking on the hours and you can see the seconds immediately change (then I click on the hour number at the top to try again).

![ezgif-7-d15e82cd09f8](https://user-images.githubusercontent.com/331330/81025947-cfb22600-8e78-11ea-827f-9e9150bb9185.gif)

**Comment by catc** [comment]
Thanks for reporting the bug. Unfortunately I don't have an ios device to test a fix but if you open a PR I can review it.

Adding the help wanted label for the time being.

**Comment by erpheus** [comment]
Today I forked the project and added some logs to try to understand the issue with the touch and click events. This is the "typical" flow of events on desktop (true in 'send change' corresponds to canAutoChangeUnit in calculatePoint):

![image](https://user-images.githubusercontent.com/331330/82121938-e3229280-9790-11ea-8c90-03143d3cd8ad.png)

And this the one on my iPhone:

![image](https://user-images.githubusercontent.com/331330/82121890-a6ef3200-9790-11ea-9efc-2632102e6370.png)

Which suggest something needs to be done in the touch handlers to let safari know that it should not trigger the click ones as well. But I wonder, doesn't this happen on android browsers too? Or do they determine whether a website has properly reacted to a touch event (to maybe send a click one) in a different way?
