### ISSUE TITLE
Typo on most of the examples

### ISSUE THREAD

**Issue by GuillaumeSpera** [catc/react-timekeeper#50]
Hi,

I just wanted to point out that most of the code from the "examples" page have typos.

importing
`import TimeKeeper from 'react-timekeeper';`
using
`<Timekeeper>`

Notice the K uppercase.

Thanks for the component :)

**Comment by catc** [comment]
Thanks for catching this - updated https://github.com/catc/react-timekeeper/commit/47ffbce73108cf3075582e3fc86b845042ecb873
