### ISSUE TITLE
When selecting a minute through the combobox the property "courseMinutes" is not being respected.

### ISSUE THREAD

**Issue by erodrigues-dev** [catc/react-timekeeper#57]
When selecting a minute through the combobox the property "courseMinutes" is not being respected.

```jsx
<TimeKeeper 
  switchToMinuteOnHourSelect
  time={value}
  onDoneClick={onClose}
  coarseMinutes={10}
  forceCoarseMinutes
  onChange={({ formatted12 }) => onChange(formatted12)}
/>
```

![image](https://user-images.githubusercontent.com/5647984/93006600-8ebbd380-f534-11ea-8546-d74fbe4bead4.png)
![image](https://user-images.githubusercontent.com/5647984/93006608-a8f5b180-f534-11ea-8028-bbdb6f895c6e.png)

**Comment by catc** [comment]
This is intended - the dropdown is meant to allow for fine grained control over minute selection so the coarse transformation shouldn't happen.

**Comment by erodrigues-dev** [comment]
Could you add an option to have the same pointers function, or an option to disable the drop-down list?
