### ISSUE TITLE
minimumTime and maximumTime

### ISSUE THREAD

**Issue by lokomass** [catc/react-timekeeper#63]
Hi,
Is there a way to set minimumTime and maximumTime please ?
Thanks

**Comment by anshul2807** [comment]
> Hi,
> Is there a way to set minimumTime and maximumTime please ?
> Thanks

Can you Explain me in brief...I'm going to work on this issue.

**Comment by catc** [comment]
Added in [v2.2.0](https://github.com/catc/react-timekeeper/releases/tag/v2.2.0)
