### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by joeyparis** [catc/react-timekeeper#75]
Attempting to use `react-timekeeper` with React 17 leads to a styling error from @emotion/core. Upgrading from emotion 10 to emotion 11 (by proxy switching from `@emotion/core` to `@emotion/react`) appears to solve this issue. However, that causes tests to fail (despite everything appearing to still work) as `enzyme` still only supports up to React 16.

There are a few options: we can use the unofficial [enzyme-adapter-react-17](https://www.npmjs.com/package/@wojtekmaj/enzyme-adapter-react-17), we can use a different testing library, or we can ignore the failed tests until Enzyme officially supports React 17, which seems like might be [relatively soon](https://github.com/enzymejs/enzyme/pull/2430#issuecomment-896499576). 

I'm happy to create a pull request for any of these options!

**Comment by catc** [comment]
Bumped react peer deps to v17 (see https://github.com/catc/react-timekeeper/commit/11a2c00af05582d5d5256c26a8eb025057597950#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R77-R79). Can you check if this is still causing issues? May need to change emotion lib too.

**Comment by catc** [comment]
Also updated emotion to v11 so this should be fixed.

**Comment by joeyparis** [comment]
All seems to be working! Thanks for this and the other recent updates :)
