### ISSUE TITLE
When selecting AM or PM it also sets minutes.

### ISSUE THREAD

**Issue by wmonecke** [catc/react-timekeeper#83]
I think the surface for selecting minutes and AM and PM are overlapping.

See here:

https://user-images.githubusercontent.com/24256469/148972959-df4c23fe-4e4d-4e34-8cab-199dfb8221c1.mov

BTW, awesome library! I will be sure to donate once my app starts making money. :)

**Comment by catc** [comment]
Is this on the most recent version? Since this issue was recently fixed (I can't seem to reproduce it).

**Comment by wmonecke** [comment]
@catc Yes, latest version fixed this. Thank you!!!
