### ISSUE TITLE
Unable to change as 24 hrs Mode

### ISSUE THREAD

**Issue by sivasasi** [catc/react-timekeeper#90]
Hi Team,

We have used this npm in our project and we want to implement timepicker in 24 HRS format, as per the documentation we have changed the code as shown below but it is still showing the time in 12 HRS format.
 
Reference :
<TimeKeeper
                time={time}
                onChange={(newTime) => setTime(newTime.formatted12)}
                hour24Mode
                coarseMinutes={15}
                forceCoarseMinutes
            />

Please find the code below for your reference.
My code: 
 <TimeKeeper hour24Mode
                    forceCoarseMinutes
                        switchToMinuteOnHourSelect
                        doneButton={(newTime) => (
                            <div
                                style={{ textAlign: 'left', padding: '10px 0' }}
                                onClick={() => alert('new time is now', newTime.formatted12)}
                            >
                                Close
                            </div>
                        )}
                        time={props.selectedPickerValue}
                        onChange={(data) => props.onTimeChange(data)}
                    />   

Are we missing something, please let us know how to use the timepicker in 24 hours format

react version details from package.json 
<img width="236" alt="TimeKeepr" src="https://user-images.githubusercontent.com/51472087/160083574-c80780c2-e7aa-4570-9078-cc0ae0ce0ed0.PNG">

"react": "^16.13.0"

**Comment by catc** [comment]
You might need to use `newTime.formatted24` if you're setting that as your time and passing it back in to the component - https://codesandbox.io/s/affectionate-firefly-srv9r5?file=/src/App.js

**Comment by sivasasi** [comment]
Hi @catc  thank you for your feedback. My issue was solved with the latest package install npm install  command  bellow: 
npm install --save react-timekeeper@latest
